/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lec2assignment;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testWithValidArgument() throws Exception {
        String argument = "test";
        ProcessBuilder processBuilder = new ProcessBuilder("microsoft", "oracle", argument);
        Process process = processBuilder.start();

        assertEquals(0, process.waitFor());
    }

    @Test
    public void testWithNoArgument() throws Exception {
        ProcessBuilder processBuilder = new ProcessBuilder("apple", "google");
        Process process = processBuilder.start();

        assertEquals(0, process.waitFor());
    }
}
