/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lec2assignment;
import java.util.Scanner;

public class App {

    static String[] Companies = {"microsoft", "apple", "oracle", "google"};
    static int max_attempts = 0;

    public static void main(String[] args) {

        boolean found = false;
        Scanner scanner = new Scanner(System.in);
        while (true) {

            if (max_attempts >= 4) {
                System.out.println("You have reached the maximium attemps!");
                break;
            }

            System.out.println("Input your guess:");
            

            String input = scanner.nextLine();

            for (String company: Companies) {
                if (input.equals(company)) {
                    System.out.printf("Bingo, it's %s\n", company);
                    found = true;
                    break;
                }
            }
            
        if (found) {
                System.out.println("Congratulations!");
                break;
            }
        
        System.out.println("Try it again!");
        max_attempts += 1;
        
        }
    
    scanner.close();

    }
}
