/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lec2assignment;
import java.util.Scanner;
import java.lang.Runtime;

public class App {

    static String[] Companies = {"microsoft", "apple", "oracle", "google"};
    static int max_attempts = 0;

    public static void main(String[] args) {
        long startTime = System.nanoTime();
        Runtime run = Runtime.getRuntime();

        boolean found = false;
        Scanner scanner = new Scanner(System.in);
        while (true) {

            long guess_start_time = System.nanoTime();
            if (max_attempts >= 4) {
                System.out.println("You have reached the maximium attemps!");
                break;
            }

            System.out.println("Input your guess:");
            

            String input = scanner.nextLine();

            for (String company: Companies) {
                if (input.equals(company)) {
                    System.out.printf("Bingo, it's %s\n", company);
                    found = true;
                    break;
                }
            }
            
            long guess_end_time = System.nanoTime();

            System.out.println("Guess time is " + Long.toString(guess_end_time - guess_start_time));
        if (found) {
                System.out.println("Congratulations!");
                break;
            }
        
        System.out.println("Try it again!");
        max_attempts += 1;
        
        }

        long endTime = System.nanoTime();
    
        scanner.close();

        long totalMemory = run.freeMemory() / 1024;
        long freeMemory = run.totalMemory() / 1024;

        System.out.println("Used memory is: " + Long.toString(totalMemory - freeMemory));
        System.out.println("Running time is " + Long.toString(endTime - startTime));


    }
}
